### ISSUE TITLE
[UI-FIX] Two buttons in Side Menu are confusing

### ISSUE THREAD

**Issue by zenkertA** [casinocoin/tokenwallet-mobile#106]
**Section or interface element**
Side Menu have Btn1 and Btn2  (see picture)

**Reason**
Those buttons are confusing, in some environments don't work reliably. If we set only one with the function most relevant it will be better.

**Description**
Btn 1: (exit icon) Logs you out.
Btn 2:  (off icon) In some phones exit the app, in others puts the app in the background, and in others simply don't do anything (iphone)

There should be only one button with homogeneous behaviour across platforms so it is not ambiguous and accomplishes its functionality.
We could get rid of Btn2 and do with Btn1 only.

**Screenshots**
![bild](https://user-images.githubusercontent.com/39646311/73194390-6fe70900-412c-11ea-982a-e93091eb089c.png)

**Comment by t3nshi** [comment]
This seems to be a bug instead of an appearance/branding correction... The first button as you can see on the icon is to log out. According to what you say it works. The second button is to exit the app. According to what you say is not working as it is only putting the app on the background. I tested on my phone. And they are working correctly. The app logs out.. and with the exit button the app closes and when I access through recent apps menu it was not on background as it loads completely again.  refer to this previous bug:  #33 
I will close this. If you still have an issue you might want to add the information required and reopen it.

**Comment by justfordaniel** [comment]
my app does not close and goes to background also

also i still dont understand why have two buttons?  logout maybe but doesnt everyone just close apps by sliding the recent apps away?

this is the same issue i was talking about yes #99

**Comment by t3nshi** [comment]
This seems to be making some people struggle.. so let's sort it out. We will adjust this functionality once and for all.
I edited the original post so it will be less ambiguous. Please  add your take so we gather people opinions and see if we finally deal with it.

**Comment by zenkertA** [comment]
Good. I have no problem with your editing the original.

Den fre 7 feb. 2020 20:36TeNsHi SaMa <notifications@github.com> skrev:

**Comment by t3nshi** [comment]
I ask the people that have interest in this to come forward and say what you think the best option is, so we consider a couple of scenarios and be able to improve on this.  We will be able to move forward as soon we have some ideas or options, and several people take a vote. Ultimately the team is the one making the decision, but nothing will change unless there are some options and votes that validate best course of action.

**Comment by t3nshi** [comment]
this will remain on hold with delayed milestone until we have some options and votes for each.
