### ISSUE TITLE
[UI-FIX] Use html5 number input for Pin number entry  

### ISSUE THREAD

**Issue by solarbeetle** [casinocoin/tokenwallet-mobile#107]
**Section or interface element**
Pin number input field

**Reason**
Invoke numeric keypad on mobile phone rather than normal text keyboard
**Description**
It's not a big deal, but currently when entering a pin number, the default text keyboard is invoked. Using the number input format would automatically invoke the number keypad, which is more suitable to this type of input

![token_wallet_keyboard](https://user-images.githubusercontent.com/26628453/73251531-0d841c00-41b1-11ea-8934-4402bf5538e3.jpg)

**Comment by t3nshi** [comment]
You are totally right there. 
The issue is that when you ask for number according to spec, you should have type number and not password. Right now we are asking for number, but since the input is type password the "browser" ignores it and we lose the keypad. We could set type password and loose the mask. Let me think on a better solution that allows the "browser" to give us the keypad without losing the mask.
![Screenshot 2020-01-28 at 08 02 16](https://user-images.githubusercontent.com/3123415/73266290-9e082f80-41a4-11ea-8058-b818714c2fdb.png)

**Comment by solarbeetle** [comment]
In your screengrab it shows inputmode="number". This should be inputmode="numeric". Hopefully that, combined with the pattern attribute you already have should fix it?

**Comment by t3nshi** [comment]
sorry about it... it is currently "tel" in the code 

``` html
<ion-input ngModel #pmctl="ngModel" clearInput required name="pincodeconfirm" type="password"  pattern="[0-9]*" inputmode="tel" minlength="6" maxlength="6" ></ion-input> 
```
(that should work the same as numeric, not number), i'm not sure how that got there...hahaha... But I found something that I'm going to try in a bit and I will let you know.

**Comment by t3nshi** [comment]
I already tried with numeric instead of "tel" just in case and it didn't worked. 😩

**Comment by t3nshi** [comment]
Found a way, I had to move things around but It will be working on next version. The catch was it was already working with tel on ios. I had me scratching my head to make it work seamlessly on both.

**Comment by solarbeetle** [comment]
Nice work!
