### ISSUE TITLE
[ADD] Finger Print Login 

### ISSUE THREAD

**Issue by CaptCrimson** [casinocoin/tokenwallet-mobile#134]
(edited)
**Is your feature request related to a problem? Please describe.**
It is a little frustrating given I trust my phone and the people that have access to it, so I should have an easier way to pass the auth instead of put the pin every time. Fingerprint is good for quick auth.

**Describe the solution you'd like**
A setting that enables auth with fingerprint instead of pin. So everytime pin is needed I will be asked for fingerprint instead.

**Describe alternatives you've considered**
another way would be a button on the pin that lets you change from auth pin to fingerprint

**Additional context**
(original info provided by original poster)

Adding a fingerprint scanner for login would be fantastic. The toast wallet had this implemented and I love idea of having that extra security than being forced to only use pin login. Consider it before launch?

Finger print scanner allows easier access and less problems with people forgetting login pin and locking themselves out.

**Comment by t3nshi** [comment]
Thanks for your issue. Next time make sure that when your request matches some of the criteria considered by the type of issue with the templates provided, you use the corresponding type and template. Otherwise, your issue might not be considered as it will lack a lot of information requested on the templates. 

This is an interesting request. But it should be filed with the FEATURE REQUEST type.
I will edit the issue to make it comply so your issue won't be closed and ignored, but keep in mind that you should use the correct type and template. You use the blank issue only when you see that none of the types fits the criteria for the problem you are reporting.

Thanks in advance. I think this is a nice feature to include.

**Comment by t-jacobi** [comment]
Thats also a nice feature for iOS!
