### ISSUE TITLE
[UI-FIX] Move Tx ID copy button and change behaviour

### ISSUE THREAD

**Issue by zenkertA** [casinocoin/tokenwallet-mobile#143]
**Section or interface element**
History/Transaction/Details the Button that copies the Tx ID should be move to the Tx ID field  and removed from it´s current position in the drop-up menu.

See edited screendump at the bottom.

**Reason**
It is hard to understand what the button really does the way it is now.
The button behaviour should also be changed to the way copy account works which gives visual feedback that it is done.
Could in fact even be enhanced with an appropriate text pop-up. 
To use on all copy buttons with the corresponding text.
In this case the text would be "Tx ID copied"

![image](https://user-images.githubusercontent.com/39646311/73852747-0489ef00-4830-11ea-9540-982eda817a6b.png)

**Comment by t3nshi** [comment]
I will check with the team. I will let you know about it later.

**Comment by zenkertA** [comment]
K. Do that ;-)

Den ons 5 feb. 2020 18:43TeNsHi SaMa <notifications@github.com> skrev:

**Comment by danielwwf** [comment]
Change as proposed by @zenkertA.

Please put the copy button on the right side.

**Comment by t3nshi** [comment]
I think in this we need to consider something important. The buttons for copy are clunky and some times get in the way and if they are small they are annoyingly untappable. So We were considering moving all copy buttons to hidden sliding options, but since they will need to be "learned"  @ajochems  and I were talking about providing the action for all on the FAB too. 
What do you think about it? may be should I prototype this and you test it out before moving on?

**Comment by danielwwf** [comment]
I like how it's now done in the test version I got which requires you to swipe it to the left. It should be kept this way for now

**Comment by t3nshi** [comment]
Great. Let's move that way for next release then. @zenkertA  please note, I will move this for the queue and it will be marked as closed once some changes are included in next version. The changes will not match exactly your request, you will check how they are done and estimate if you have no longer a problem. If you feel you do you may reopen this at that point or maybe add a new issue since this might be already outdated.

**Comment by zenkertA** [comment]
OK
