### ISSUE TITLE
[UI-FIX] - Top left logo is markable

### ISSUE THREAD

**Issue by t-jacobi** [casinocoin/tokenwallet-mobile#149]
**Section or interface element**
If you tab on the top left casinocoin icon it will be marked with a blue border. This should not happen because its not necessary.

**Reason**
-

**Description**
A clear and concise description of how the look and feel should be.

**Screenshots**
![IMG_2521](https://user-images.githubusercontent.com/46750418/73977688-1603f180-492b-11ea-8b96-a262558bb439.png)

**Comment by t3nshi** [comment]
Yes that is right. Well spotted. I will try to provide a fix for next version.

**Comment by t-jacobi** [comment]
Not solved in 0.1.15 on ios 13.3.1

**Comment by t3nshi** [comment]
EDITED:::
I'm sorry!
LOL I just verified and it was misreported as solved. I did it yesterday, it seems it got mixed with other issue. My bad.
Sorry about that!!!


~~Nowhere in here we said that it would be solved on 0.1.15... this is not even included in a milestone yet. The version 0.1.15 solved many previous issues that were reported and solved during last week this issue Is not being addressed yet. Pay attention to the staging as well as the milestones and you will be aware of when to expect it to be fixed.~~

**Comment by t3nshi** [comment]
I will put the correct milestone. This is what happens when you are arrogant enough to say things without checking them carefully first

**Comment by t-jacobi** [comment]
Thats okay, mostly if a lot of issues came across! Go ahead with your great work!

**Comment by t3nshi** [comment]
thanks man, sorry for the hasty erroneous reply,
