### ISSUE TITLE
[UI-FIX] - Transaction & wallet details confusing

### ISSUE THREAD

**Issue by t-jacobi** [casinocoin/tokenwallet-mobile#155]
**Section or interface element**
Detail view of an transaction or wallet

**Reason**
The normal view of your eyes is basically top down and left to right (instead in the arab regions its right to left).

**Description**
To avoid the left to right or right to left reading direction all informations should be among each other. (Best view is currently on the separate product...)

**Screenshots**
Look in the sep. product ;-)

**Comment by t3nshi** [comment]
I know what you mean with separate product. But I don't undersand anything else at all. If it helps, send me a private message on discord. I will fix this according to what you relay there. thanks.

**Comment by t-jacobi** [comment]
This is the layout in this app:
![IMG_2525](https://user-images.githubusercontent.com/46750418/74084947-794d6b00-4a74-11ea-9487-2796fb10305b.png)

**Comment by t3nshi** [comment]
You posted an explanation for the things that are already clear.. I need  you to explain and elaborate what you want, try to be especific. You are talking left to right but your improvement is not clear. Maybe I will close this and you post using the template, where you have to explain and provide examples... If you can, use screenshots.... but I will remove screenshots that are not from this app. Thanks.

**Comment by t-jacobi** [comment]
Put each Label/Value pair in one line. With more space between each line. Never have more then one Label/Value Box in one line. Thats what i mean :-)

**Comment by t3nshi** [comment]
Since there were some changes in this screens lately I will ask you to check on the next version and come back here and let us now if you still have a problem, since you are expressing thinks that are not clearly presenting a problem  but rather a personal preference, If you still find yourself needing changes I will suggest you get more people interested in those changes. I will be waiting for your feedback once you are able to check next version so we decide if we keep this open or if we will close it.

**Comment by t3nshi** [comment]
I will close this now. If you find yourself needing this again please reopen it and provide additional information or get more people on this. Thanks in advance
