### ISSUE TITLE
[UI-FIX] - Remove option to switch theme in hamburger menu

### ISSUE THREAD

**Issue by t-jacobi** [casinocoin/tokenwallet-mobile#158]
**Section or interface element**
Hamburger menu

**Reason**
Reducing the menu like "lesser is more". You already have the option in Settings. 

**Description**
Remove the toggle out of the menu and leave it in the settings dialog. 

**Screenshots**
Illustrate current look and feel. Or provide commented pictures, or 
edited screens to see how it should look like. Be clear about which picture is edited

**Comment by t3nshi** [comment]
I think this is smart. It will be better. In UX design lesser is more is not a rule, because lesser sometimes is confusing and frustrating. But lesser sometimes is less ambiguous and optimal. In this case I think it will be the latter. Let me check with the team and I will get back here to let you know if we will  implement it.

**Comment by danielwwf** [comment]
Change as proposed by @t-jacobi.

**Comment by t3nshi** [comment]
For sure!
