### ISSUE TITLE
[UI-FIX] - Remove FAB menu in transaction details

### ISSUE THREAD

**Issue by t-jacobi** [casinocoin/tokenwallet-mobile#161]
**Section or interface element**
Transaction details view - FAB menu

**Reason**
I think is redundant

**Description**
In the TA view you have two copy icons directly on the field you want to copy. 
Why have a separate menu (FAB menu) to copy Transaction ID or open CSC observer? 
If you put the label (sep. Ticket here) above the ID you have enough space to put the glass and the copy icon at the end of the transaction ID. 

**Screenshots**
none

**Comment by t3nshi** [comment]
I don't understand this. Please elaborate so I can reproduce it and be able to help you. Thanks in advance.

**Comment by t3nshi** [comment]
After you commented and added more information on other issue I understood this one a bit better since I got what bubble meant for you. I edited your issue to make it readable and less ambiguous.

Now about the issue itself...

Actually the actions were initially single buttons. But the layout was messy and full of clutter. When we added the FAB (Floating Action Button) to the app flow, it got way better. FABs are today emblematic UI pieces as outstanding and popular apps are using them almost anyone is already familiar with the way they work. In this case, we should provide any action available on a screen with FAB in the FAB. We are thinking on adding a couple of more actions here, but we are not yet sure. I will talk to the team about removing FAB in case we wont add anything else, and what impact could get in UX in general.

**Comment by t-jacobi** [comment]
Great, now i know how to call this menu ;-)

**Comment by t3nshi** [comment]
We internally decided that we will keep the option to copy transaction id on the FAB since the copy buttons are now slide options. If you think this still should be addressed please reopen the issue and give your reasoning or explanation. Thanks in advance.
