### ISSUE TITLE
[UI-FIX] - remove copy option in FAB menu (account details)

### ISSUE THREAD

**Issue by t-jacobi** [casinocoin/tokenwallet-mobile#162]
**Section or interface element**
wallet detail view

**Reason**
You already have an context sensitive copy button that copies the account id. you can remove the button from the bubble menu. 

**Description**
A clear and concise description of how the look and feel should be.

**Screenshots**
Illustrate current look and feel. Or provide commented pictures, or 
edited screens to see how it should look like. Be clear about which picture is edited

**Comment by t3nshi** [comment]
I don't think this is clear. Maybe can you provide a screenshot?

**Comment by t-jacobi** [comment]
In the bubble menu is a copy icon ... at first use you dont know what it will copy -> bad experience. But you have already a button in the line of the account id. Based on that you can remove the icon in the bubble menu.

![IMG_2523](https://user-images.githubusercontent.com/46750418/74041599-3df46300-49c6-11ea-81f9-410250f7ad65.png)

**Comment by t3nshi** [comment]
Thanks! that is crystal clear. I will talk to the team and will get back to you. I think we are considering some way to improve the UX for the copy button on form, since in a lot of devices was difficult to click, we made it bigger and now for some is getting in the way. It could be moved to swipe option later. If we do this, it will not be as evident, so we need to provide alternatives. Besides, to be consistent across the app we are providing FAB button ( I never understood that bubble thing until now), with full actions we have available on a specific screen. So if there is an action we should be able to do it through FAB button to provide some consistency.
Your suggestion even though might be on spot. Let me discuss it a bit. I'll let you know. thanks for the additional clarification

**Comment by t3nshi** [comment]
since right now we are moving to hidden copy button, for some it will be easier to have this button available on the FAB menu. So please, check this when you get a chance to get next version and let us know if we need to reopen this.
