### ISSUE TITLE
[UI-FIX] Dashboard alignment problem only on iOS

### ISSUE THREAD

**Issue by danielwwf** [casinocoin/tokenwallet-mobile#165]
**Section or interface element**
Dasboard

**Reason**
Render issue Dashboard details cause of keyboard. There is a gap. Network/Market details are cut.

**Description**
Should look like droid.

**Screenshots**
![image](https://user-images.githubusercontent.com/30388756/74090157-a7e53900-4aa8-11ea-84f3-77f8396edcc0.png)

**Comment by t3nshi** [comment]
I was aware of this and spent a huge chunk of my time yesterday on it. But currently is not trivial providing a solution, since it varies a lot from one screen size to another. So when I solve it for Iphone XR is not good on Iphone 4. So I am currently looking for a way to replace the layout and have a seamless look on all devices. I will update in here as soon as there is some progress.
