### ISSUE TITLE
[ADD] Exiting app using back button

### ISSUE THREAD

**Issue by HolyK1cks** [casinocoin/tokenwallet-mobile#176]
(EDITED)
**Is your feature request related to a problem? Please describe.**
I was trying to exit the app, and is it not as easy as in other apps. And I got to the login page but the app didn't exit at all.

**Describe the solution you'd like**
I would like to just press hardware back button on login screen and the app closes.

**Describe alternatives you've considered**
another way could be pressing twice the back button so I don't exit by mistake, But this could work anywhere in the app. It could have popup message so I know when the app is about to close and I can confirm so I don't do it by mistake

**Additional context**
Almost every app can be closed using the back button, so I think this  one should be able to.

**Comment by t3nshi** [comment]
Please fill the form if you want your request considered thanks. you should provide not only what is requested but a meaningful title to avoid duplicates.

**Comment by t3nshi** [comment]
I took the time to check, and try to understand what you meant here. Got some additional clues from discord, so I will just edit your issue this time, so it will be considered. I won't do that next time. So please consider providing all information requested next time. Thanks

**Comment by danielwwf** [comment]
Most apps allow closing by tapping back twice, we should go for this.
Might be different on iOS

**Comment by t3nshi** [comment]
We were discussing about it earlier and the most recent spec establish that the system is responsible of exiting an app not the app itself, so, recent versions of android and ios won't be closed as well, but put on background. Due to this behaviour, we already removed the close app button from the side menu as well. Check this for some info about it: https://stackoverflow.com/a/26399886/2857334,
We won't rely on features that will only work for some or in half of devices. We need an app that work homogeneously similar across many devices.
