### ISSUE TITLE
[UI-FIX] - Not translatable strings

### ISSUE THREAD

**Issue by t-jacobi** [casinocoin/tokenwallet-mobile#196]
1. "Fiat Value:" in dashboard not translatable
2. "Active/Inactive"-Status in wallet view not translatable
3. "Default CSC Account", "CSC Account" in wallet view not translatable
4. Touch ID message box label not translate able
5. "Connection to blockchain..."-Message after login not translateable
6. "Import account" button in Settings not translatable

Maybe they are but the key:value pair in the en.json is missing.

**Comment by t3nshi** [comment]
You may be right. I will look into this to validate and will let you know later

**Comment by t3nshi** [comment]
I fixed these and many more that where also orphan. But for instance, Import account was already on the translations file. There are some that we will see how they work. Like CSC Default Account... If you change the language it won't change after used since it is assigned to the Label. I will try to have all of them for next release.
