### ISSUE TITLE
[UI-FIX] - Use currency symbols instead of text

### ISSUE THREAD

**Issue by t-jacobi** [casinocoin/tokenwallet-mobile#202]
**Section or interface element**
Setting dialog for changing the currency that should be used for calculations

**Reason**
No need for translation

**Description**
Fix the currency in sourcecode and remove the translation in the l18n files. 

**Screenshots**
-

**Comment by t3nshi** [comment]
Please try to fill the templates properly, Sometimes we can infer what you are saying, others it is just so ambiguous!!!  So... as I've been warning others,  issue template incomplete will be discarded and the issue closed. 

Now, about this issue. Are you saying that instead of USD, GBP, EUR, JPY in currencies we put something like... $,£,€,¥? so what about for example, canadian dolars, australian dolars? how do we diferentiate them from USD since they are different currencies?  I think we need to keep it as it currently is.

**Comment by t-jacobi** [comment]
hi @t3nshi hmm you're right. I did not think about that it was out of the translation glass ;-) i close the issue.
