### ISSUE TITLE
Can’t delete active address in IOS mobile wallet

### ISSUE THREAD

**Issue by iamkhomani** [casinocoin/tokenwallet-mobile#219]

**Comment by t3nshi** [comment]
When reporting an issue you must select one of the templates provided so your issue won't be dismissed without consideration. 
There are issues that won't fit any of the templates provided, but that will be clear with the complete, concise and detailed description provided that, in this case, is entirely missing.

Sometimes I will help  someone posting their first issue by trying to infer and providing what I can in one of the templates. In this case you only put a title, so I won't do any effort on the template, let me try to 
infer from that title what you were trying to do.

I will guess what you are reporting with just that titile is that you didn't find any way to delete an account. Well that is of course, because we don't provide such functionality. Every account added to the blockchain will be there forever, and to reflect that on the wallet, once you add an account to the wallet you are not able to delete it.

Of course you might be looking for something else, but if that's the case, you failed to convey it with just a title.

If your issue is related to something else, please take your time to fill properly a template giving all the requested information. Otherwise we won't consider your problem. 

Let's think it this way, why would we bother putting time and effort exploring whatever you stumble upon if you won't take the time to even explain and provide details so we understand unambiguously what is happening and we are able to replicate it ourselves?

I will close this now, don't bother replying here. If your issue is the one I guessed or if it is different and you want it considered you will post something with full information in a new issue.

Thanks for being willing to help us improve.
