### ISSUE TITLE
Potential CasinoCoin Wallet Issue

### ISSUE THREAD

**Issue by blocksmaster2025** [casinocoin/tokenwallet-mobile#227]
Hi,

I just wanted to bring a potential issue to your attention so you can take a look.

Today I wanted to move some CSC from my BRM to my CasinoCoin Wallet.

**Steps taken**

1. Launch the CasinoCoin Wallet
2. Select the Account for my csc to be transferred into
3. Click the CasinoCoin icon (bottom right)
4. Select Receive csc
5. Select 'Share Account ID String'
6. Click on 'copy to clipboard'
7. I would then goto the BRM to paste the destination address however the address is invalid

The reason for this is that when I copy the Account ID String to the clipboard it is adding this string to the beginning of the actual account ID: CasinoCoin CSC Account ID:

This isn't a big problem as I noticed the issue and removed the string from the beginning of the paste but this could cause some issues and not a great experience.

Just wanted you to be aware in case it needs looking at.

I am on Android.

Thanks, Steve.
Discord ID: lazzareo#9559

**Comment by t3nshi** [comment]
Please check you are in the correct project when reporting a issue, This was misplaced on the desktop wallet.

When sharing to social media (that's the main use of the share button) you have additional text. If you want to just get the accountID text you can use the copy button instead of the share button. and it is even a shorter path. instead of selecting receive on the bubble menu you select the first copy option. The accountID string will be on the clipboard so you just have to paste it on the BRM app.

If this does not resolve your issue or you find that your issue still needs to be dealt with, please take your time to provide complete information by following the respective template and maybe providing  screenshots. 

Thanks for taking your time and helping us improve our project.
