### ISSUE TITLE
[BUG] Settings Menu wont close

### ISSUE THREAD

**Issue by danielwwf** [casinocoin/tokenwallet-mobile#46]
**Describe the bug**
On smaller devices, it's hard to close the settings page as there is no "empty" space to tap in. It should be possible to close it by swiping right.

**To Reproduce**
1. Open Setting Page on a small device

**Expected behavior**
The menu should close if I swipe right.

**Screenshots**
![image](https://user-images.githubusercontent.com/30388756/72574707-40353700-38ca-11ea-87b9-210a7a01a4ce.png)

**Smartphone (please complete the following information):**
 - Device: Moto Play7
 - OS: Android
 - OS Version 9
 - App Version 0.1.4

**Comment by t3nshi** [comment]
The swipe was deactivated because any swipe for other functions would activate or deactivate the menu, and it is a bad UI design and is a current comon standard to avoid swipe enabled menu. to close menu you have to tap on the gap with the backdrop where there are no menu. It was the same on the BRM it was already deactivated

**Comment by justfordaniel** [comment]
yes this is same as #95 

it would be fine to press the whole top logo area to close....    it is because of a small device also.....  some other way to close other than hitting the thin slither on the left would be nice if no swipe .... i would just make the whole logo area close it personally
