### ISSUE TITLE
Log out Buton does not work

### ISSUE THREAD

**Issue by danielwwf** [casinocoin/tokenwallet-mobile#6]
The logout button has no function.

![image](https://user-images.githubusercontent.com/30388756/71724989-a3d35500-2e32-11ea-9c54-d4beec7d51e6.png)

**Comment by t3nshi** [comment]
**Describe the bug**
In the side menu, when tap the logout button it does nothing

**To Reproduce**
Steps to reproduce the behavior:
1. Tap menu to swipe on the side menu
2. Tap on logout button
3. Nothing happens
4. User is still logged in

**Expected behavior**
When the logout button is tapped the user should be logged off from app
also  there should be a button to exit the app



**Smartphone (please complete the following information):**
 - Device: Moto Z2 Force
 - OS: android 7
 - App Version  0.0.9

**Comment by t3nshi** [comment]
will be fixed in the next PR

**Comment by t3nshi** [comment]
fixed on #24
