### ISSUE TITLE
[UI-FIX] loading bar weird and off centre

### ISSUE THREAD

**Issue by justfordaniel** [casinocoin/tokenwallet-mobile#92]
![Screenshot_2](https://user-images.githubusercontent.com/57195813/73142128-3ad2ac00-4083-11ea-87e0-80540505f83e.png)
**Section or interface element**

the loading bar is off centre and loads outwards? the button is also out a bit

**Reason**
Explain why this adjustment improves the look and feel 
or how it will align with branding guidelines

**Description**
if it loads outwards instead of left to right it should be in the centre i think

**Screenshots**
Illustrate current look and feel. Or provide commented pictures, or 
edited screens to see how it should look like. Be clear about which picture is edited

**Comment by t3nshi** [comment]
The bar is not accounting for exact progress of the process. It is intended to work that way so the user is aware of the process being done, but since we are not providing information on current progress the animation moves the bar forward and backwards... Please let me know if I understood your statement or if not, please provide additional information so we can deal with it more accurately. Thanks in advance.

**Comment by t3nshi** [comment]
Additionaly, you are quite right on the alignment of the button. I will look into it to include a fix for next version.

**Comment by t3nshi** [comment]
The bar will stay as it is, but the alignment of the button will be available on next upcoming version. thank you!

**Comment by justfordaniel** [comment]
np,
the bar moving graphic is not centre also tho.... why i was not sure if it was on purpose or not
