### ISSUE TITLE
[UI-FIX]  I would like to change FAB to Form Buttons on Contact page

### ISSUE THREAD

**Issue by justfordaniel** [casinocoin/tokenwallet-mobile#94]
![Screenshot_8](https://user-images.githubusercontent.com/57195813/73142212-15926d80-4084-11ea-98f5-6b9cabb1a6ac.png)
**Section or interface element**
the extra menu logo is off centre.....however, i dont think this menu is necessary tbh.  the extra buttons could appear in another form at the top of the page

**Description**
i feel like this menu looks like it was added on as an afterthought, no offence.  the plus contact could easy be at the top.  so could barcode scan.
same on history page, there is plenty of space for the search button.
i feel like this extra menu button takes away from the consistency of the design but that is just my opinion
in the wallet section, those options to add token and add account could be at the bottom or always attached below the last account or even at the top.   

**Screenshots**
Illustrate current look and feel. Or provide commented pictures, or 
edited screens to see how it should look like. Be clear about which picture is edited

**Comment by t3nshi** [comment]
We appreciate your opinion! thanks. You are mostly right, initially we had form buttons in here, but it was more on the opposite direction, we added the FAB to align to the rest of the functionality and UX as we had on the app, and this change was implemented after many suggested. As you said, it is just your opinion, but it could be the opinion of others as well. So far, since you are proposing this change against others that suggested otherwise, I would think we can leave this around for a while and see if there are others that aggree with your opinion. We might consider changing it then. 😄

**Comment by justfordaniel** [comment]
im not sure quite what you mean about form and FAB

pic of the old one?

anyway, i appreciate ppl may prefer it out of the way.  i would still suggest a different graphic......
opposite colours and square so...
a clear box with slightly bevelled corners with a red outlign
a red logo
and a small solid red triangle on top of the box pointing upwards 
inline with the contacts also as current one is not aligned 
i would also make it a bit smaller and with no drop shadow

just my thoughts lol

**Comment by justfordaniel** [comment]
or another idea......  this could be considered a bit out there? who knows? but...

you could delete it and instead ....   when you tap on contacts......
the contact button changes to a different menu button so if you click it again it could display above or as an overlay to the base menu?
just another idea

**Comment by t3nshi** [comment]
I'm not sure I quite understand everything you just wrote here...

> im not sure quite what you mean about form and FAB
> 
> pic of the old one?
> 
> anyway, i appreciate ppl may prefer it out of the way. i would still suggest a different graphic......
> opposite colours and square so...
> a clear box with slightly bevelled corners with a red outlign
> a red logo
> and a small solid red triangle on top of the box pointing upwards
> inline with the contacts also as current one is not aligned
> i would also make it a bit smaller and with no drop shadow
> 
> just my thoughts lol

So let me explain a bit. Right now apps and practices around them had evolved and their creation itself also evolved. There are people that spend a lot of time coming up with new and creative ideas to provide ease of use and a great experience on their apps. Most of the time an idea that is innovative by itself takes time to gain traction, sometimes people don't understand or instead of easier it becomes harder for users (remember windows 8) sometimes the app itself provides something that became so widespread that they dictate new rules (apps had changed much due to instagram and facebook).
We will need to provide for a large userbase, so we will play it safe. Using interfaces that are being already adopted by the public, because are already widespread. Simplifying interaction using "the current most standard way". 
For example the FAB stands for Floating Action Button, and it is described in the material design spec from google. It became so widespread, that not only google apps and android apps following the material design guidelines are using it. You will see many apps everywhere using them as they provide simplicity and are mostly intuitive (given you used one of those apps before). 
We are open and welcome good suggestion that could bring good impact on the UX (user experience) on our app, but we need to maintain and follow guidelines for the design and for the functionality. If we can meet halfway there it will be great. Let's keep this discussion open for a while, if we gather more opinions that could help us improve we will surely include them in our design.

**Comment by justfordaniel** [comment]
.
.
if you need this button i would prefer it more like this below
.
.
![cscmobilepreclicknoarrow](https://user-images.githubusercontent.com/57195813/73600297-19bc0080-4546-11ea-861f-d2b3ba8c6d58.png)
.
.
.
.
or with small arrow as below 
.
.

![cscmobilepreclickwitharrow](https://user-images.githubusercontent.com/57195813/73600308-4112cd80-4546-11ea-8a6c-40c30199e74e.png)
.
.
.
.
.
on click something like this below, but i would make the button look like it is sunken into the page now
.
.
.
![cscmobileonclick](https://user-images.githubusercontent.com/57195813/73600313-4cfe8f80-4546-11ea-945e-eebd60a466ea.png)
.
.
.
.
or button could appear like this below....  this double arrow should not have the grey box around it obviously but i just plonked it on there as an example 
.
.
.

![cscwalletbutton2opt](https://user-images.githubusercontent.com/57195813/73600330-89ca8680-4546-11ea-8547-36a37237668d.png)

then on click it would say contacts again and display options above

and the search bar would wider now

**Comment by t3nshi** [comment]
awesome your approach and providing all this ideas. Let's see what others think. I still think the current FAB keeps the consistency of the app a little more than what you suggest, but let's see what other people say about it.

**Comment by justfordaniel** [comment]
sure, i agree in some way because the icons i downloaded are not a match to the design but the main thing i prefer is the button shape/(or re-use of contact button)  and the way the options are displayed larger

**Comment by t3nshi** [comment]
I am really ok with the state this is in. IMHO the current buttons are OK. Since this has been open for a while now, and we are not seeing anyone with a similar request or supporting this, I will suggest that you talk to others and find some support for this this week, Otherwise, If this stays quiet still, I will close it by the end of this week.

**Comment by justfordaniel** [comment]
sure np.  i would obviously prefer an alternative to the button but thats just my preference lol so its not a big deal as it functions as is.  what i will say is that if any update or improvements to this structure are being considered in future that please consider the 'menu options' of filling the page in some way like the example i provided because i didn't know what all of the options did until i clicked them and they are very small also.  when they fill the page there is plenty of room for text descriptions and they are easy to tap. just an idea anyhow.  happy for you to close this, thanks for your time
